# Generated by Django 5.2.1 on 2026-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='balance_pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
