# Generated by Django 5.2.4 on 2026-03-30 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_game_offertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.game'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.offertype'),
        ),
    ]
