# Generated by Django 5.2.1 on 2026-03-29 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('payment_pending', 'payment_pending'), ('paid', 'paid'), ('delivered', 'delivered'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('dispute', 'dispute')], default='payment_pending', max_length=32)),
                ('payment_method', models.CharField(default='manual_bank', max_length=64)),
                ('payment_provider', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_marked_paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_at_purchase', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.product')),
            ],
        ),
    ]
