# Generated by Django 5.2.1 on 2026-03-30 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_pending_status(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='payment_pending').update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id_alter_orderitem_id_alter_order_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_pending_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('delivered', 'delivered'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('dispute', 'dispute')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='SellerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('hold', 'Hold'), ('available', 'Available'), ('paid_out', 'Paid Out')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seller_transactions',
                'constraints': [models.UniqueConstraint(fields=('seller', 'order'), name='unique_seller_transaction_per_order')],
            },
        ),
    ]
