# Generated by Django 5.2.4 on 2026-03-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_product_price_gt_0_and_more'),
        ('orders', '0005_alter_order_total_alter_orderitem_price_at_purchase'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orderitem_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_at_purchase__gte', 0)), name='orderitem_price_at_purchase_gte_0'),
        ),
    ]
