# Generated by Django 5.2.4 on 2026-03-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_orderitem_quantity_gt_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellertransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
