# Generated by Django 5.2.4 on 2026-03-30 23:20

import django.db.models.deletion
from django.db import migrations, models


def backfill_order_item_snapshots(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")

    for order_item in OrderItem.objects.select_related("product").all():
        product = getattr(order_item, "product", None)
        if not product:
            continue

        images = getattr(product, "images", []) or []
        order_item.product_title_snapshot = product.title
        order_item.product_image_snapshot = images[0] if images else ""
        order_item.save(
            update_fields=["product_title_snapshot", "product_image_snapshot"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seed_games_category'),
        ('orders', '0007_sellertransaction_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image_snapshot',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_title_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product'),
        ),
        migrations.RunPython(backfill_order_item_snapshots, migrations.RunPython.noop),
    ]
